src/Entity/Carpools.php
<?php

namespace App\Entity;

use App\Repository\CarpoolsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CarpoolsRepository::class)]
class Carpools
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $day = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTime $begin = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTime $end = null;

    #[ORM\Column(length: 255)]
    private ?string $address_start = null;

    #[ORM\Column(length: 255)]
    private ?string $address_end = null;


    #[ORM\Column]
    private ?int $places_available = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column(type: 'string', length: 100, columnDefinition: "ENUM('A venir', 'En cours', 'Terminé', 'Confirmé', 'Vérification par la plateforme') NOT NULL DEFAULT 'A venir'")]
    private $status = 'A venir';

    #[ORM\ManyToOne(inversedBy: 'carpools')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Drivers $driver = null;

    #[ORM\ManyToOne(inversedBy: 'carpools')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Cars $car = null;

     /**
      * @var Collection<int, Users>
      */
     #[ORM\ManyToMany(targetEntity: Users::class, inversedBy: 'carpools')]
     private Collection $user;

    #[ORM\Column(length: 255)]
    private ?string $carpool_number = null;

    #[ORM\Column]
    private ?bool $isEcological = null;

    #[ORM\Column]
    private ?int $duration = null;

    /**
     * @var Collection<int, Reviews>
     */
    #[ORM\OneToMany(targetEntity: Reviews::class, mappedBy: 'carpool', orphanRemoval: true)]
    private Collection $reviews;

    /**
     * @var Collection<int, CarpoolsUsers>
     */
    #[ORM\OneToMany(targetEntity: CarpoolsUsers::class, mappedBy: 'carpool', orphanRemoval: true)]
    private Collection $carpoolsUsers;

    #[ORM\Column(name: 'startLat', type: 'float', nullable: true)]
    private ?float $startLat = null;

    #[ORM\Column(name: 'startLon', type: 'float', nullable: true)]
    private ?float $startLon = null;

    #[ORM\Column(name: 'endLat', type: 'float', nullable: true)]
    private ?float $endLat = null;

    #[ORM\Column(name: 'endLon', type: 'float', nullable: true)]
    private ?float $endLon = null;

    public function __construct()
    {
        $this->user = new ArrayCollection();
        $this->reviews = new ArrayCollection();
        $this->carpoolsUsers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDay(): ?\DateTime
    {
        return $this->day;
    }

    public function setDay(\DateTime $day): static
    {
        $this->day = $day;

        return $this;
    }

    public function getBegin(): ?\DateTime
    {
        return $this->begin;
    }

    public function setBegin(\DateTime $begin): static
    {
        $this->begin = $begin;

        return $this;
    }

    public function getEnd(): ?\DateTime
    {
        return $this->end;
    }

    public function setEnd(\DateTime $end): static
    {
        $this->end = $end;

        return $this;
    }

    public function getAddressStart(): ?string
    {
        return $this->address_start;
    }

    public function setAddressStart(string $address_start): static
    {
        $this->address_start = $address_start;

        return $this;
    }

    public function getAddressEnd(): ?string
    {
        return $this->address_end;
    }

    public function setAddressEnd(string $address_end): static
    {
        $this->address_end = $address_end;

        return $this;
    }

    public function getPlacesAvailable(): ?int
    {
        return $this->places_available;
    }

    public function setPlacesAvailable(int $places_available): static
    {
        $this->places_available = $places_available;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getDriver(): ?Drivers
    {
        return $this->driver;
    }

    public function setDriver(?Drivers $driver): static
    {
        $this->driver = $driver;

        return $this;
    }

    public function getCar(): ?Cars
    {
        return $this->car;
    }

    public function setCar(?Cars $car): static
    {
        $this->car = $car;

        return $this;
    }

    /**
      * @return Collection<int, Users>
      */
     public function getUser(): Collection
     {
         return $this->user;
     }

     public function addUser(Users $user): static
     {
         if (!$this->user->contains($user)) {
             $this->user->add($user);
         }

         return $this;
     }

     public function removeUser(Users $user): static
     {
         $this->user->removeElement($user);

         return $this;
     }

    public function getCarpoolNumber(): ?string
    {
        return $this->carpool_number;
    }

    public function setCarpoolNumber(string $carpool_number): static
    {
        $this->carpool_number = $carpool_number;

        return $this;
    }

    /**
     * @return Collection<int, Reviews>
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Reviews $review): static
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews->add($review);
            $review->setCarpool($this);
        }

        return $this;
    }

    public function removeReview(Reviews $review): static
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getCarpool() === $this) {
                $review->setCarpool(null);
            }
        }

        return $this;
    }

    /**
     * Get the value of isEcological
     */ 
    public function getIsEcological()
    {
        return $this->isEcological;
    }

    /**
     * Set the value of isEcological
     *
     * @return  self
     */ 
    public function setIsEcological($isEcological)
    {
        $this->isEcological = $isEcological;

        return $this;
    }

    /**
     * @return Collection<int, CarpoolsUsers>
     */
    public function getCarpoolsUsers(): Collection
    {
        return $this->carpoolsUsers;
    }

    public function addCarpoolsUser(CarpoolsUsers $carpoolsUser): static
    {
        if (!$this->carpoolsUsers->contains($carpoolsUser)) {
            $this->carpoolsUsers->add($carpoolsUser);
            $carpoolsUser->setCarpool($this);
        }

        return $this;
    }

    public function removeCarpoolsUser(CarpoolsUsers $carpoolsUser): static
    {
        if ($this->carpoolsUsers->removeElement($carpoolsUser)) {
            // set the owning side to null (unless already changed)
            if ($carpoolsUser->getCarpool() === $this) {
                $carpoolsUser->setCarpool(null);
            }
        }

        return $this;
    }

    public function getStartLat(): ?float
    {
        return $this->startLat;
    }

    public function setStartLat(float $startLat): static
    {
        $this->startLat = $startLat;

        return $this;
    }

    public function getStartLon(): ?float
    {
        return $this->startLon;
    }

    public function setStartLon(float $startLon): static
    {
        $this->startLon = $startLon;

        return $this;
    }

    public function getEndLat(): ?float
    {
        return $this->endLat;
    }

    public function setEndLat(float $endLat): static
    {
        $this->endLat = $endLat;

        return $this;
    }

    public function getEndLon(): ?float
    {
        return $this->endLon;
    }

    public function setEndLon(float $endLon): static
    {
        $this->endLon = $endLon;

        return $this;
    }

    /**
     * Get the value of duration
     */ 
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * Set the value of duration
     *
     * @return  self
     */ 
    public function setDuration($duration)
    {
        $this->duration = $duration;

        return $this;
    }
}

src/Controller/Admin/CarpoolController.php
<?php

namespace App\Controller\Admin;

use App\Form\CreateCarpoolForm;
use App\Repository\CarpoolsRepository;
use App\Security\Voter\CarpoolsVoter;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

#[Route('/admin/carpool', name: 'app_admin_carpool_')]
class CarpoolController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(CarpoolsRepository $carpoolsRepository, Security $security): Response
    {
        // check if User have 'ROLE_ADMIN'
        if (!$security->isGranted('ROLE_ADMIN')) {
            throw $this->createAccessDeniedException('Seul un administrateur peut accéder aux avis.');
        }

        $showCarpools = $carpoolsRepository->showNextCarpools();

        return $this->render('admin/carpool/index.html.twig', [
            'carpools' => $showCarpools,
        ]);
    }

    #[Route('/edit/{carpoolNumber}', name: 'edit', methods: ['GET', 'POST'])]
    public function editCarpool(
        $carpoolNumber,
        CarpoolsRepository $carpoolsRepository,
        AuthorizationCheckerInterface $authChecker,
        Request $request,
        EntityManagerInterface $em
    ): Response {

        $carpools = $carpoolsRepository->findOneBy(['carpool_number' => $carpoolNumber]);
        if (!$carpools) {
            throw $this->createNotFoundException('Covoiturage non trouvé.');
        }
        $driver = $carpools->getDriver();

        $driverCars = $driver ? $driver->getCars() : [];

        // Vérify if Admin can Edit
        if (!$authChecker->isGranted(CarpoolsVoter::EDIT, $carpools)) {
            throw $this->createAccessDeniedException('Vous n\'avez pas le droit de modifier ce covoiturage.');
        }

        $carpoolForm = $this->createForm(CreateCarpoolForm::class, $carpools, [
            'driver_car' => $driverCars,
        ]);

        $carpoolForm->handleRequest($request);

        if ($carpoolForm->isSubmitted() && $carpoolForm->isValid()) {
            $em->flush();
            $this->addFlash('success', 'Le covoiturage a été modifié.');
            return $this->redirectToRoute('app_admin_carpool_index');
        }

        return $this->render('admin/carpool/edit.html.twig', [
            'carpoolForm' => $carpoolForm->createView(),
            'carpools' => $carpools,
            'driver_car' => $driverCars,
            'google_maps_api_key' => $_SERVER['GOOGLE_MAPS_API_KEY'] ?? $_ENV['GOOGLE_MAPS_API_KEY'] ?? null,
        ]);
    }
}

templates/carpool/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails du covoiturages
{% endblock %}


{% block importmap %}
	{{ importmap(['app', 'detailsCarpool']) }}
{% endblock %}
{% block javascripts %}
	{# base.html.twig JS block #}
	{{ parent() }}

	<script src="https://maps.googleapis.com/maps/api/js?key={{ google_maps_api_key }}&callback=initMap&loading=async" async></script>
{% endblock %}


{% block body %}
	<main>
		<h1 class="text-center mt-3">Détails du covoiturage</h1>
		<section class="container flux mt-5">
			<h2 class="mb-3">Votre véhicule</h2>
			<div class="table-responsive">
				<table class="table table-striped table-success">
					<thead>
						<tr>
							<th>Marque</th>
							<th>Modèle</th>
							<th>Couleur</th>
							<th>Plaque</th>
							<th>Energie</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>{{ carpool.car.brand }}</td>
							<td>{{ carpool.car.model }}</td>
							<td>{{ carpool.car.color }}</td>
							<td>{{ carpool.car.PlateNumber }}</td>
							<td>{{ carpool.car.energy }}</td>
						</tr>
					</tbody>
				</table>
			</div>
		</section>
		<section class="container flux mt-3">
			<h2>Informations</h2>
			<div class="container mt-5 mb-5 col-lg-6 col-md-6 col-sm-10">
				<div class="card shadow-lg">
					<div class="card-body">
						<div class="border-bottom pb-3 mb-2">
							<div class="d-flex flex-wrap align-items-center justify-content-between">
								<div class="me-4 mb-2">
									<span class="fw-bold">Jour :</span>
									<span>{{ carpool.day|date('d/m/Y') }}</span>
								</div>
								<div class="me-4 mb-2">
									<span class="fw-bold">Trajet écologique :</span>
									<span>
										{% if carpool.isEcological %}
											Oui
										{% else %}
											Non
										{% endif %}
									</span>
								</div>
								<div class="me-4 mb-2">
									<span class="fw-bold">Heure de départ :</span>
									<span>{{ carpool.begin|date('H:i') }}</span>
								</div>
								<div class="me-4 mb-2">
									<span class="fw-bold">Heure d'arrivée :</span>
									<span>{{ carpool.end|date('H:i') }}</span>
								</div>
							</div>
						</div>
						<div class="d-flex mt-3">
							<span class="fw-bold me-lg-2 mb-1 mb-lg-0">Prix :</span>
							<span>{{ carpool.price }}
								Crédits</span>
						</div>
					</div>
				</div>
			</div>
		</section>
		<section class="container flux">
			<div class="row">
				<div class="col-lg-6 mx-auto">
					<div class="d-flex justify-content-center">
						{% if not app.user %}
							<a href="{{ path('app_login') }}" class="btn btn-primary">Se connecter pour réserver</a>
						{% elseif not app.user.isPassenger %}
							<p class="text-danger fs-5">Un chauffeur ne peut pas réserver</p>
						{% elseif carpool.PlacesAvailable == 0 %}
							<p class="text-danger fs-5">Plus de places disponibles</p>
						{% elseif app.user.credits >= carpool.price %}
							<button class="btn btn-secondary w-100" data-bs-toggle="modal" data-bs-target="#confirmationModal">Réserver</button>
						{% else %}
							<p class="text-danger text-center fs-5">Crédits insuffisants pour réserver</p>
						{% endif %}
					</div>
				</div>
			</div>
		</section>
		<section class="container flux mt-3">
			<h2>Votre chauffeur</h2>
			<div id="guide-details" class="container mt-5 mb-5 col-lg-6 col-md-6 col-sm-10">
				<div class="card shadow-lg">
					<div class="card-body">
						<div class="border-bottom pb-3 mb-2 d-flex align-items-center">
							<div class="ms-3">
								{% if carpool.driver.user.photo %}
									<img id="guide-image" src="{{ carpool.driver.user.photo ? asset('uploads/users/mini/40x40-' ~ carpool.driver.user.photo) : asset('/images/favicon.png') }}" alt="Photo du guide" class=" rounded-circle" width="100" height="100">
								{% else %}
									<i class="fa fa-user-circle fs-2"></i>
								{% endif %}
							</div>
							<div class="ms-4">
								<span class="fw-bold">{{ carpool.driver.user.pseudo }}</span>
								<div class="d-flex align-items-center mt-2 flex-wrap">
									<span class="fw-bold me-2">
										{% if averageRating is not null %}
											{{ averageRating|number_format(1) }}/5
										{% else %}
											-/5
										{% endif %}
									</span>
									<i class="fa-solid fa-star text-secondary me-3"></i>
									<a href="{{ path('app_review_details', { 'pseudo': carpool.driver.user.pseudo }) }}" class="text-warning fw-bold d-block d-md-inline mt-2 mt-md-0">
										<b>{{ totalReviews }}
											Avis</b>
									</a>
								</div>
							</div>
						</div>
						<div>
							<span>
								<b>Fumeur :</b>
							</span>
							<span>
								{% if carpool.driver.smoking %}
									Oui
								{% else %}
									Non
								{% endif %}
							</span><br><br>
							<span>
								<b>Animaux:</b>
							</span>
							<span>
								{% if carpool.driver.animals %}
									Oui
								{% else %}
									Non
								{% endif %}
							</span><br><br>
							<span>
								<b>Ptéférences :</b>
							</span>
							<span>{{ carpool.driver.preferences }}</span>
						</div>
					</div>
				</div>
			</div>
		</section>
		<section class="container flux mb-5">
			<h2 class="mb-4">Aperçu du trajet</h2>
			<div class="card shadow-lg mb-4">
				<div class="card-body">
					<div class="row align-items-center mb-3">
						<div class="col-12 col-md-6 d-flex align-items-center mb-2 mb-md-0">
							<span class="fw-bold me-2 text-info">
								<i class="fa-solid fa-play"></i>
								Départ :
							</span>
							<span>{{ carpool.addressStart }}</span>
						</div>
						<div class="col-12 col-md-6 d-flex align-items-center">
							<span class="fw-bold me-2 text-success">
								<i class="fa-solid fa-flag-checkered"></i>
								Arrivée :
							</span>
							<span>{{ carpool.addressEnd }}</span>
						</div>
					</div>
					<div class="row">
						<div class="col-12">
							<div id="map" class="map-all w-100" data-address-start="{{ carpool.addressStart|e('html_attr') }}" data-address-end="{{ carpool.addressEnd|e('html_attr') }}"></div>
							<div class="fs-5" id="route-info"></div>
						</div>
					</div>
				</div>
			</div>
		</section>
	</main>
	<!-- Modals -->
	{% include "_partials/modals/user/confirm_reservation_modals.html.twig" %}
{% endblock %}

templates/carpool/results.html.twig
{% extends 'base.html.twig' %}

{% block title %}Résultats de votre recherche
{% endblock %}

{% block importmap %}
	{{ importmap(['app', 'listMap']) }}
{% endblock %}
{% block javascripts %}
	{# base.html.twig JS block #}
	{{ parent() }}
	<script src="https://maps.googleapis.com/maps/api/js?key={{ google_maps_api_key }}&callback=initMap&loading=async" async></script>
{% endblock %}

{% block body %}
<main class="wrapper">
    <section class="container mb-5">
        <h1 class="ms-3 text-center mt-5">Résultats de recherche</h1>
        <p class="text-center">Cliquez sur le vovoiturage pour plus de détails</p>
        <div class="d-flex justify-content-end mb-3">
            <button id="tabList" class="btn btn-info me-2 active">Liste</button>
            <button id="tabMap" class="btn btn-success">Carte</button>
        </div>

        <div id="listView">
            <div class="row">
                <!-- Filtres -->
                <div class="d-lg-none mb-3">
                    <button class="btn btn-info w-100" type="button" data-bs-toggle="collapse" data-bs-target="#filtersCollapse" aria-expanded="false" aria-controls="filtersCollapse">
                        Filtres
                    </button>
                </div>
                <div class="col-12 col-lg-3 mb-3 mb-lg-0 border-end border-2">
                    <div class="collapse d-lg-block" id="filtersCollapse">
                        <h2>Filtres</h2>
                        {% if carpools is not empty %}
                            {% include '_partials/_search_filters.html.twig' %}
                        {% else %}
                            <p class="fs-5">Aucun filtre disponible</p>
                        {% endif %}
                    </div>
                </div>
                <!-- Results -->
                <div id="results" class="col-12 col-lg-9">
                    {% if carpools is not empty %}
                        <div class="row justify-content-center">
                            {% for carpool in carpools %}
                                <div class="mt-5 col-lg-8 col-md-9 col-sm-10">
                                    <div class="card shadow-lg card-guide">
                                        <a href="{{ path('app_carpool_details', {carpoolNumber: carpool.carpoolNumber}) }}" target="_blank">
                                            <div class="card-body">
                                                <div class="row mb-2 border-bottom pb-2">
                                                    <div class="col-lg-4">
                                                        <strong>Date :</strong>
                                                        {{ carpool.day|date('d/m/Y') }}
                                                    </div>
                                                    <div class="col-lg-4">
                                                        <strong>Départ :</strong>
                                                        <span>{{ carpool.begin|date('H:i') }}</span>
                                                    </div>
                                                    <div class="col-lg-4">
                                                        <strong>Fin :</strong>
                                                        <span>{{ carpool.end|date('H:i') }}</span>
                                                    </div>
                                                    <div class="col-lg-4">
                                                        <strong>Ecologique :</strong>
                                                        {% if carpool.isEcological %}
                                                            Oui
                                                        {% else %}
                                                            Non
                                                        {% endif %}
                                                    </div>
                                                    <div class="col-lg-4">
                                                        <strong>Place restante(s) :</strong>
                                                        {{ carpool.placesAvailable }}
                                                    </div>
                                                    <div class="col-lg-4">
                                                        <b>Durée :</b>
                                                        {% if carpool.duration is not null %}
                                                            {% set hours = (carpool.duration / 3600)|round(0, 'floor') %}
                                                            {% set minutes = ((carpool.duration % 3600) / 60)|round(0, 'floor') %}
                                                            {% if hours > 0 %}
                                                                {{ hours }}h
                                                            {% endif %}
                                                            {{ minutes }}min
                                                        {% else %}
                                                            non renseigné
                                                        {% endif %}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=" ms-2 mb-2 d-flex align-items-center">
                                                {% if carpool.driver.user.photo %}
                                                    <img src="{{ asset('uploads/users/mini/40x40-' ~ carpool.driver.user.photo) }}" class="rounded-circle" alt="Photo de profil" class="profile-picture">
                                                {% else %}
                                                    <i class="fa fa-user-circle fs-2"></i>
                                                {% endif %}
                                                <div class="ms-1">
                                                    <strong>
                                                        {{ carpool.driver.user.pseudo }}
                                                    </strong>
                                                </div>
                                                <div class="ms-2">
                                                    <span class="fw-bold me-2" id="guide-note">
                                                        {% if carpool.averageRating is not null %}
                                                            {{ carpool.averageRating|number_format(1) }}/5
                                                        {% else %}
                                                            -/5
                                                        {% endif %}
                                                    </span>
                                                </div>

                                                <div class="ms-3">
                                                    <strong>Prix :</strong>
                                                    {{ carpool.price }}
                                                    Crédits
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        <div class="fs-5 text-center pt-5 row">
                            {% if carpools is empty %}
                                <div class="fs-5 text-center pt-5 row">
                                    {% if nearestDay is defined and nearestDay is not null %}
                                        <p>Nous n'avons aucun covoiturage disponible pour la date choisie.</p>
                                        <p>Date la plus proche disponible&nbsp;:</p>
                                        <a class="text-secondary fw-bold" href="{{ path('app_carpool_results', app.request.query.all | merge({ day: nearestDay|date('Y-m-d') }) ) }}">
                                            {{ nearestDay|date('d/m/Y') }}
                                        </a>
                                    {% else %}
                                        Nous n'avons aucun covoiturage disponible avec vos critères de recherche.
                                    {% endif %}
                                </div>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div id="mapView" class="map-list">
        </div>
    </section>
</main>
{% endblock %}