src/Entity/Carpools.php
<?php

namespace App\Entity;

use App\Repository\CarpoolsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CarpoolsRepository::class)]
class Carpools
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $day = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTime $begin = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTime $end = null;

    #[ORM\Column(length: 255)]
    private ?string $address_start = null;

    #[ORM\Column(length: 255)]
    private ?string $address_end = null;


    #[ORM\Column]
    private ?int $places_available = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column(type: 'string', length: 100, columnDefinition: "ENUM('A venir', 'En cours', 'Terminé', 'Confirmé', 'Vérification par la plateforme') NOT NULL DEFAULT 'A venir'")]
    private $status = 'A venir';

    #[ORM\ManyToOne(inversedBy: 'carpools')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Drivers $driver = null;

    #[ORM\ManyToOne(inversedBy: 'carpools')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Cars $car = null;

     /**
      * @var Collection<int, Users>
      */
     #[ORM\ManyToMany(targetEntity: Users::class, inversedBy: 'carpools')]
     private Collection $user;

    #[ORM\Column(length: 255)]
    private ?string $carpool_number = null;

    #[ORM\Column]
    private ?bool $isEcological = null;

    #[ORM\Column]
    private ?int $duration = null;

    /**
     * @var Collection<int, Reviews>
     */
    #[ORM\OneToMany(targetEntity: Reviews::class, mappedBy: 'carpool', orphanRemoval: true)]
    private Collection $reviews;

    /**
     * @var Collection<int, CarpoolsUsers>
     */
    #[ORM\OneToMany(targetEntity: CarpoolsUsers::class, mappedBy: 'carpool', orphanRemoval: true)]
    private Collection $carpoolsUsers;

    #[ORM\Column(name: 'startLat', type: 'float', nullable: true)]
    private ?float $startLat = null;

    #[ORM\Column(name: 'startLon', type: 'float', nullable: true)]
    private ?float $startLon = null;

    #[ORM\Column(name: 'endLat', type: 'float', nullable: true)]
    private ?float $endLat = null;

    #[ORM\Column(name: 'endLon', type: 'float', nullable: true)]
    private ?float $endLon = null;

    public function __construct()
    {
        $this->user = new ArrayCollection();
        $this->reviews = new ArrayCollection();
        $this->carpoolsUsers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDay(): ?\DateTime
    {
        return $this->day;
    }

    public function setDay(\DateTime $day): static
    {
        $this->day = $day;

        return $this;
    }

    public function getBegin(): ?\DateTime
    {
        return $this->begin;
    }

    public function setBegin(\DateTime $begin): static
    {
        $this->begin = $begin;

        return $this;
    }

    public function getEnd(): ?\DateTime
    {
        return $this->end;
    }

    public function setEnd(\DateTime $end): static
    {
        $this->end = $end;

        return $this;
    }

    public function getAddressStart(): ?string
    {
        return $this->address_start;
    }

    public function setAddressStart(string $address_start): static
    {
        $this->address_start = $address_start;

        return $this;
    }

    public function getAddressEnd(): ?string
    {
        return $this->address_end;
    }

    public function setAddressEnd(string $address_end): static
    {
        $this->address_end = $address_end;

        return $this;
    }

    public function getPlacesAvailable(): ?int
    {
        return $this->places_available;
    }

    public function setPlacesAvailable(int $places_available): static
    {
        $this->places_available = $places_available;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getDriver(): ?Drivers
    {
        return $this->driver;
    }

    public function setDriver(?Drivers $driver): static
    {
        $this->driver = $driver;

        return $this;
    }

    public function getCar(): ?Cars
    {
        return $this->car;
    }

    public function setCar(?Cars $car): static
    {
        $this->car = $car;

        return $this;
    }

    /**
      * @return Collection<int, Users>
      */
     public function getUser(): Collection
     {
         return $this->user;
     }

     public function addUser(Users $user): static
     {
         if (!$this->user->contains($user)) {
             $this->user->add($user);
         }

         return $this;
     }

     public function removeUser(Users $user): static
     {
         $this->user->removeElement($user);

         return $this;
     }

    public function getCarpoolNumber(): ?string
    {
        return $this->carpool_number;
    }

    public function setCarpoolNumber(string $carpool_number): static
    {
        $this->carpool_number = $carpool_number;

        return $this;
    }

    /**
     * @return Collection<int, Reviews>
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Reviews $review): static
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews->add($review);
            $review->setCarpool($this);
        }

        return $this;
    }

    public function removeReview(Reviews $review): static
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getCarpool() === $this) {
                $review->setCarpool(null);
            }
        }

        return $this;
    }

    /**
     * Get the value of isEcological
     */ 
    public function getIsEcological()
    {
        return $this->isEcological;
    }

    /**
     * Set the value of isEcological
     *
     * @return  self
     */ 
    public function setIsEcological($isEcological)
    {
        $this->isEcological = $isEcological;

        return $this;
    }

    /**
     * @return Collection<int, CarpoolsUsers>
     */
    public function getCarpoolsUsers(): Collection
    {
        return $this->carpoolsUsers;
    }

    public function addCarpoolsUser(CarpoolsUsers $carpoolsUser): static
    {
        if (!$this->carpoolsUsers->contains($carpoolsUser)) {
            $this->carpoolsUsers->add($carpoolsUser);
            $carpoolsUser->setCarpool($this);
        }

        return $this;
    }

    public function removeCarpoolsUser(CarpoolsUsers $carpoolsUser): static
    {
        if ($this->carpoolsUsers->removeElement($carpoolsUser)) {
            // set the owning side to null (unless already changed)
            if ($carpoolsUser->getCarpool() === $this) {
                $carpoolsUser->setCarpool(null);
            }
        }

        return $this;
    }

    public function getStartLat(): ?float
    {
        return $this->startLat;
    }

    public function setStartLat(float $startLat): static
    {
        $this->startLat = $startLat;

        return $this;
    }

    public function getStartLon(): ?float
    {
        return $this->startLon;
    }

    public function setStartLon(float $startLon): static
    {
        $this->startLon = $startLon;

        return $this;
    }

    public function getEndLat(): ?float
    {
        return $this->endLat;
    }

    public function setEndLat(float $endLat): static
    {
        $this->endLat = $endLat;

        return $this;
    }

    public function getEndLon(): ?float
    {
        return $this->endLon;
    }

    public function setEndLon(float $endLon): static
    {
        $this->endLon = $endLon;

        return $this;
    }

    /**
     * Get the value of duration
     */ 
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * Set the value of duration
     *
     * @return  self
     */ 
    public function setDuration($duration)
    {
        $this->duration = $duration;

        return $this;
    }
}

src/Controller/Driver/AccountController.php
<?php

namespace App\Controller\Driver;

use App\Entity\Drivers;
use App\Entity\Users;
use App\Form\DriverPreferencesForm;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/driver/account', name: 'app_driver_account_')]
class AccountController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(Request $request, EntityManagerInterface $em): Response
    {
         /** @var Users $user */
        $user = $this->getUser();

        $driver = $em->getRepository(Drivers::class)->findOneBy(['user' => $user]);

        $driverForm = $this->createForm(DriverPreferencesForm::class, $driver);

        $driverForm->handleRequest($request);

        if ($driverForm->isSubmitted() && $driverForm->isValid()) {

            $em->persist($driver);
            $em->flush();

            $this->addFlash('success', 'Votre profil de chauffeur a été mis à jour.');

            return $this->redirectToRoute('app_driver_account_index');
        }

        return $this->render('driver/account/index.html.twig', [
            'driverForm' => $driverForm->createView(),
        ]);
    }
}

src/Controller/Driver/CarController.php
<?php

namespace App\Controller\Driver;

use App\Entity\Cars;
use App\Repository\DriversRepository;
use App\Repository\CarsRepository;
use App\Form\DriverCarForm;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Security\Voter\CarsVoter;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

#[Route('/driver/car', name: 'app_driver_car_')]
class CarController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(Request $request, EntityManagerInterface $em, DriversRepository $driversRepository): Response
    {
        /** @var Users $user */
        $user = $this->getUser();

        // Create new Cars object
        $car = new Cars();

        $carForm = $this->createForm(DriverCarForm::class, $car);

        // get the driver ID associate with the user ID
        $driver = $driversRepository->findOneBy(['user' => $user]);

        // if driver don't exist
        if (!$driver) {
            $this->addFlash('error', 'Vous devez être un chauffeur pour ajouter un véhicule.');
            return $this->redirectToRoute('app_user_account_index');
        }

        $carForm->handleRequest($request);

        if ($carForm->isSubmitted() && $carForm->isValid()) {

            $car->setDriver($driver);

            $em->persist($car);
            $em->flush();

            $this->addFlash('success', 'Votre véhicule a été ajouté avec succès.');

            return $this->redirectToRoute('app_driver_car_list');
        }

        return $this->render('driver/car/index.html.twig', [
            'carForm' => $carForm->createView(),
        ]);
    }

    #[Route('/list', name: 'list')]
    public function list(DriversRepository $driversRepository): Response
    {
        /** @var Users $user */
        $user = $this->getUser();

        $driver = $driversRepository->findOneBy(['user' => $user]);
        if (!$driver) {
            $this->addFlash('error', 'Vous devez être un chauffeur pour voir vos véhicules.');
            return $this->redirectToRoute('app_user_account_index');
        }

        // get the cars of the User
        $cars = $driver->getCars();

        return $this->render('driver/car/list.html.twig', [
            'cars' => $cars
        ]);
    }

    #[Route('/edit/{id}', name: 'edit', methods: ['GET', 'POST'])]
    public function editCars(
        $id,
        CarsRepository $carsRepository,
        AuthorizationCheckerInterface $authChecker,
        Request $request,
        EntityManagerInterface $em
    ): Response {
        $car = $carsRepository->find($id);
        if (!$car) {
            throw $this->createNotFoundException('Véhicule non trouvé.');
        }

        // Vérify if the Driver is the owner
        if (!$authChecker->isGranted(CarsVoter::EDIT, $car)) {
            throw $this->createAccessDeniedException('Vous n\'avez pas le droit de modifier ce véhicule.');
        }

        $carForm = $this->createForm(DriverCarForm::class, $car);
        
        $carForm->handleRequest($request);

        if ($carForm->isSubmitted() && $carForm->isValid()) {
            $em->flush();
            $this->addFlash('success', 'Le véhicule a été modifié.');
            return $this->redirectToRoute('app_driver_car_list');
        }

        return $this->render('driver/car/edit.html.twig', [
            'carForm' => $carForm->createView(),
            'car' => $car,
        ]);
    }

    #[Route('/delete/{id}', name: 'delete', methods: ['POST'])]
    public function deleteCars(
        $id,
        CarsRepository $carsRepository,
        AuthorizationCheckerInterface $authChecker,
        EntityManagerInterface $em
    ): Response {
        $car = $carsRepository->find($id);
        if (!$car) {
            throw $this->createNotFoundException('Véhicule non trouvé.');
        }

        if (!$authChecker->isGranted(CarsVoter::DELETE, $car)) {
            throw $this->createAccessDeniedException('Vous n\'avez pas le droit de supprimer ce véhicule.');
        }

        $em->remove($car);
        $em->flush();

        $this->addFlash('success', 'Le véhicule a été supprimé.');
        return $this->redirectToRoute('app_driver_car_list');


        return $this->render('driver/car/edit.html.twig', [
        ]);
    }
}

src/Controller/Driver/RegistrationController.php
<?php

namespace App\Controller\Driver;

use App\Entity\Cars;
use App\Entity\Users;
use App\Entity\Drivers;
use App\Form\DriverCarForm;
use App\Form\DriverPreferencesForm;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

#[Route('/driver/registration', name: 'app_driver_registration_')]
class RegistrationController extends AbstractController
{

    private TokenStorageInterface $tokenStorage;

    public function __construct(TokenStorageInterface $tokenStorage)
    {
        $this->tokenStorage = $tokenStorage;
    }

    #[Route('/preferences', name: 'preferences')]
    public function addPreferences(Request $request, EntityManagerInterface $em): Response
    {
        // get User
        /** @var Users $user */
        $user = $this->getUser();

        $driver = $em->getRepository(Drivers::class)->findOneBy(['user' => $user]);

        // Create new Drivers object, create driver_id and link it to the User
        if (!$driver) {
            $driver = new Drivers();
            $driver->setUser($user);
        }


        $driverForm = $this->createForm(DriverPreferencesForm::class, $driver);

        $driverForm->handleRequest($request);

        if ($driverForm->isSubmitted() && $driverForm->isValid()) {

            $em->persist($driver);
            $em->flush();

            return $this->redirectToRoute('app_driver_registration_car');
        }


        return $this->render('driver/registration/index.html.twig', [
            'driverForm' => $driverForm->createView(),
        ]);
    }

    #[Route('/car', name: 'car')]
    public function addCar(Request $request, EntityManagerInterface $em): Response
    {
        /** @var Users $user */
        $user = $this->getUser();

        // Get the driver link to the User
        $driver = $em->getRepository(Drivers::class)->findOneBy(['user' => $user]);

        if (!$driver) {
            throw $this->createNotFoundException('Profil chauffeur introuvable.');
        }

        $car = new Cars();
        $car->setDriver($driver);

        $carForm = $this->createForm(DriverCarForm::class, $car);

        $carForm->handleRequest($request);

        if ($carForm->isSubmitted() && $carForm->isValid()) {
            $em->persist($car);

            // Add ["ROLE_DRIVER"] when User give all information needed
            $roles = $user->getRoles();
            if (!in_array('ROLE_DRIVER', $roles)) {
                $roles[] = 'ROLE_DRIVER';
                $user->setRoles($roles);
            }

            $em->flush();

            $this->addFlash('success', 'Votre inscription comme chauffeur a été validée.');


            $this->tokenStorage->setToken(
                new UsernamePasswordToken($user, 'main', $user->getRoles())
            );


            return $this->redirectToRoute('app_driver_account_index');
        }

        return $this->render('driver/registration/car.html.twig', [
            'carForm' => $carForm->createView(),
        ]);
    }
}

templates/_partials/modals/driver/delete_cars_modals.html.twig
<div class="modal fade" id="deleteModal-{{ car.id }}" tabindex="-1" aria-labelledby="deleteModalLabel-{{ car.id }}" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="cancelModalLabel">Supprimer véhicule</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<p>
					<strong>Êtes-vous sûr de vouloir supprimer votre véhicule</strong>?</p>
				<p>
					<strong>marque :</strong>
					{{ car.brand }}
                </p>
				<p>
					<strong>Modèle :</strong>
					{{ car.model }}</p>
		</div>
		<div class="modal-footer">
			<form method="POST" action="{{ path('app_driver_car_delete', { id: car.id }) }}">
				<button type="submit" class="btn btn-danger">Supprimer</button>
			</form>
		</div>
	</div>
</div></div>

templates/_partials/modals/driver/driver_cancel_carpools_modals.html.twig
<div class="modal fade" id="deleteModal-{{ carpool.id }}" tabindex="-1" aria-labelledby="deleteModalLabel-{{ carpool.id }}" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="cancelModalLabel">Annulation de covoiturage-{{ carpool.carpoolNumber }}</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<p>
					<strong>Êtes-vous sûr de vouloir annuler votre covoiturage</strong>?</p>
				<p>
					<strong>Prix :</strong>
					{{ carpool.price }}
					crédits</p>
				<p>
					<strong>Date :</strong>
					{{ carpool.day|date('d/m/Y') }}</p>
				<p>
					<strong>Place restante(s):</strong>
					{{ carpool.placesAvailable }}</p>
				<p>
					<strong>Nom voyageur(s) :</strong>
					{% for user in carpool.user %}
						<span>{{ user.pseudo }}</span>
					{% else %}
						<span>Aucune réservation</span>
					{% endfor %}
				</p>
		</div>
		<div class="modal-footer">
			<form method="POST" action="{{ path('app_driver_carpool_cancel', { id: carpool.id }) }}">
				<button type="submit" class="btn btn-danger">Annuler réservation</button>
			</form>
		</div>
	</div>
</div></div>

templates/_partials/modals/driver/driver_confirm_end_modals.html.twig
<div class="modal fade" id="endModal-{{ carpool.id }}" tabindex="-1" aria-labelledby="endModalLabel-{{ carpool.id }}" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="endModalLabel-{{ carpool.id }}">Finir le covoiturage -
					{{ carpool.carpoolNumber }}</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<p>
					<strong>Êtes-vous sûr de vouloir terminer votre covoiturage</strong>?</p>

				<p>
					<strong>Date :</strong>
					{{ carpool.day|date('d/m/Y') }}</p>
				<p>
					<strong>Heure d'arrivée' :</strong>
					{{ carpool.end|date('H:i') }}</p>

				<p>
					<strong>Nom passager(s) :</strong>
					{% for user in carpool.user %}
						<span>{{ user.pseudo }}</span>
					{% else %}
						<span>Aucune réservation</span>
					{% endfor %}
				</p>
			</div>
			<div class="d-flex justify-content-between modal-footer">
				<form method="POST" action="{{ path('app_driver_carpool_end', { id: carpool.id }) }}">
					<button type="submit" class="btn btn-info">Terminer</button>
				</form>
			</div>
		</div>
	</div>
</div>

templates/_partials/modals/driver/driver_confirm_start_modals.html.twig
<div class="modal fade" id="startModal-{{ carpool.id }}" tabindex="-1" aria-labelledby="startModalLabel-{{ carpool.id }}" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="cancelModalLabel">Débuter le covoiturage-{{ carpool.carpoolNumber }}</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<p>
					<strong>Êtes-vous sûr de vouloir commencer votre covoiturage</strong>?</p>

				<p>
					<strong>Date :</strong>
					{{ carpool.day|date('d/m/Y') }}</p>
				<p>
					<strong>Heure de départ :</strong>
					{{ carpool.begin|date('H:i') }}</p>

				<p>
					<strong>Nom voyageur(s) :</strong>
					{% for user in carpool.user %}
						<span>{{ user.pseudo }}</span>
					{% else %}
						<span>Aucune réservation</span>
					{% endfor %}
				</p>
			</div>
			<div class="d-flex justify-content-between modal-footer">
				<form method="POST" action="{{ path('app_driver_carpool_start', { id: carpool.id }) }}">
					<button type="submit" class="btn btn-info">Début</button>
				</form>
			</div>
		</div>
	</div>
</div>